version: '3.8'
services:
  sun_travel_angular-service:
    container_name: sun_travel_angular-container
    build: 
      context: ./frontend/sun-Travel
      dockerfile: Dockerfile
    volumes:
      - ./frontend/sun-Travel:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      #specify host port :container port
      - "4200:80"
    command: sh -c "npm start"
  sun_travel_mysql-standalone:
    image: mysql:latest
    container_name: sun_travel_mysql-container
    environment: [
      -MYSQL_ROOT_PASSWORD=admin123
      -MYSQL_DATABASE=sun_travels
      -MYSQL_USER=root
      -MYSQL_PASSWORD=password1234
      ]
  sun_travel_springboot-service:
    container_name: sun_travel_springboot-container
    ports:
      - 8080:8080
    build:
      context: ./backend/demo
      dockerfile: Dockerfile
    depends_on:
      - sun_travel_mysql-standalone



     

