#Secrete
apiVersion: v1
kind: Secret
metadata:
  name: mysql-db-credentials
type: Opaque
data:
  username: dGVzdFVzZXI= #echo -n 'testUser'|base64
  password: cGFzc3dvcmQxMjM0   #echo -n 'password1234'|base64

